.\" Manpage for mc-server.
.\" Contact me in https://github.com/AlexProgrammerDE/Minecraft-Server in a issue to correct errors or typos.
.TH man 1 "04 Dec 2019" "1.2.3" "mc-server man page"
.SH NAME
mc-server 
.SH SYNOPSIS
mc-server [OPTIONS]
.SH DESCRIPTION
mc-server is a command-line dialog tool for creating Minecraft Server easily.
.SH OPTIONS
You can add -s to automatically start your created server. mc-server also accets -h and-v
.SH SEE ALSO
dialog(1)
.SH WEB-SITE
https://github.com/AlexProgrammerDE/Minecraft-Server
.SH BUGS
No known bugs.
.SH AUTHOR
AlexProgrammerDE
